export enum IntentType {
  ADD_TRANSACTION = "ADD_TRANSACTION",
  QUERY_EXPENSES = "QUERY_EXPENSES",
  QUERY_INCOME = "QUERY_INCOME",
  QUERY_BALANCE = "QUERY_BALANCE",
  QUERY_CARD_INVOICE = "QUERY_CARD_INVOICE",
  QUERY_BILLS = "QUERY_BILLS",
  QUERY_INVESTMENTS = "QUERY_INVESTMENTS",
  DELETE_TRANSACTION = "DELETE_TRANSACTION",
  DELETE_CARD_TRANSACTION = "DELETE_CARD_TRANSACTION",
  PAY_BILL = "PAY_BILL",
  PAY_CARD_INVOICE = "PAY_CARD_INVOICE",
  ADD_INVESTMENT = "ADD_INVESTMENT",
  REDEEM_INVESTMENT = "REDEEM_INVESTMENT",
  TOGGLE_NOTIFICATIONS = "TOGGLE_NOTIFICATIONS",
  HELP = "HELP",
  UNKNOWN = "UNKNOWN",
}

export type IntentResult = {
  intent: IntentType;
  confidence: number;
  parameters?: Record<string, any>;
};
